name: movies
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.1.3
  flutter_riverpod: ^2.4.9
  get_it: ^7.6.0
  shared_preferences: ^2.1.0
  cached_network_image: ^3.2.0
  reactive_forms: ^16.1.1
  dio: ^5.4.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.3
  flutter_native_splash: ^2.4.0
  logger: ^1.3.0
  geolocator: ^12.0.0
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_barcode_scanning: ^0.12.0
  camera: ^0.10.5+3
  image_picker: ^1.1.2
  image_editor: ^1.5.1
  photo_view: ^0.14.0
  image_painter: ^0.6.0

flutter_native_splash:
  color: "#000000"
  image: assets/icons/logo.jpeg

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
